/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinesys.ui;

import com.cinesys.DAO.VeDAO;
import com.cinesys.entity.Ve1;
import com.cinesys.untils.MsgBox;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;

/**
 *
 * @author Hoàng Xuân Sáng
 */
public class QuanLyVe extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyVe
     */
    public QuanLyVe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVe = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JCheckBoxMenuItem();
        mniDoiMatKhau = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniThoat = new javax.swing.JCheckBoxMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniQuanLyVe = new javax.swing.JMenuItem();
        mniQuanLyPhim = new javax.swing.JMenuItem();
        mniQuanLyLichChieu = new javax.swing.JMenuItem();
        mniQuanLySuatChieu = new javax.swing.JMenuItem();
        mniQuanLyPhongChieu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniQuanLyKhachHang = new javax.swing.JMenuItem();
        mniQuanLyNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDanSuDung = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ VÉ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm")));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        tblVe.setBackground(new java.awt.Color(102, 255, 204));
        tblVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Vé", "Gía Vé", "Ngày Mua", "Mã Ghế", "Mã KH", "Mã NV", "Mã SC", "Mã Phim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVe);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnPrint.setText("Xuất file");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnPrint)))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/cinema-post.jpg"))); // NOI18N

        mnuHeThong.setText("Hệ Thống");

        mniDangXuat.setText("Đăng Xuất");
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Log out.png"))); // NOI18N
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);

        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Refresh.png"))); // NOI18N
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator1);

        mniThoat.setText("Thoát");
        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Stop.png"))); // NOI18N
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản Lý");

        mniQuanLyVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Ticket.png"))); // NOI18N
        mniQuanLyVe.setText("Quản lý vé");
        mniQuanLyVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyVeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQuanLyVe);

        mniQuanLyPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Film-projector.png"))); // NOI18N
        mniQuanLyPhim.setText("Quản lý phim");
        mnuQuanLy.add(mniQuanLyPhim);

        mniQuanLyLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/schedule.png"))); // NOI18N
        mniQuanLyLichChieu.setText("Quản lý lịch chiếu");
        mnuQuanLy.add(mniQuanLyLichChieu);

        mniQuanLySuatChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/management-30.png"))); // NOI18N
        mniQuanLySuatChieu.setText("Quản lý suất chiếu");
        mnuQuanLy.add(mniQuanLySuatChieu);

        mniQuanLyPhongChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/cinema-30.png"))); // NOI18N
        mniQuanLyPhongChieu.setText("Quản lý phòng chiếu");
        mnuQuanLy.add(mniQuanLyPhongChieu);
        mnuQuanLy.add(jSeparator2);

        mniQuanLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/customer-30.png"))); // NOI18N
        mniQuanLyKhachHang.setText("Quản lý khách hàng");
        mnuQuanLy.add(mniQuanLyKhachHang);

        mniQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/staff-30.png"))); // NOI18N
        mniQuanLyNhanVien.setText("Quản lý nhân viên");
        mniQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQuanLyNhanVien);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setText("Thống Kê");
        jMenuBar1.add(mnuThongKe);

        mnuTroGiup.setText("Trợ Giúp");

        mniHuongDanSuDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/training-30.png"))); // NOI18N
        mniHuongDanSuDung.setText("Hướng dẫn sử dụng");
        mnuTroGiup.add(mniHuongDanSuDung);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniQuanLyVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniQuanLyVeActionPerformed

    private void mniQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniQuanLyNhanVienActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        this.fillTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        // TODO add your handling code here:
        this.xuatFile();
    }//GEN-LAST:event_btnPrintMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyVe dialog = new QuanLyVe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JCheckBoxMenuItem mniDangXuat;
    private javax.swing.JCheckBoxMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniHuongDanSuDung;
    private javax.swing.JMenuItem mniQuanLyKhachHang;
    private javax.swing.JMenuItem mniQuanLyLichChieu;
    private javax.swing.JMenuItem mniQuanLyNhanVien;
    private javax.swing.JMenuItem mniQuanLyPhim;
    private javax.swing.JMenuItem mniQuanLyPhongChieu;
    private javax.swing.JMenuItem mniQuanLySuatChieu;
    private javax.swing.JMenuItem mniQuanLyVe;
    private javax.swing.JCheckBoxMenuItem mniThoat;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JTable tblVe;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    void init() {
        setLocationRelativeTo(null);

        this.fillTable();
    }
    VeDAO dao = new VeDAO();// làm việc vs bảng vé
    int row = -1;// hàng đc chọn hiện tại trên bảng

    void fillTable() { // đổ dữ liệu vào table Ve
        DefaultTableModel model = (DefaultTableModel) tblVe.getModel();
        model.setRowCount(0); // xóa tất cả các hàng trên JTable
        try {
            String keyword = txtSearch.getText();
            List<Ve1> list = dao.selectByKeyword(keyword);// đọc dữ liệu từ CSDL
            System.out.println("11");
            for (Ve1 v : list) {
                Object[] row = {
                    v.getMaVe(),
                    v.getGiaVe(),
                    v.getNgayMua(),
                    v.getMaGhe(),
                    v.getMaKH(),
                    v.getMaNV_TaiKhoan(),
                    v.getMaLC(),
                    v.getMaPhim()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    void update() {
        // btnUpdate
        try {
            int n = tblVe.getRowCount();
            for (int i = 0; i < n; i++) {
                int MaVe = (Integer) tblVe.getValueAt(i, 0);
                Ve1 v = dao.selectById(MaVe);
                v.setGiaVe(Integer.parseInt((String) tblVe.getValueAt(i, 1)));
                dao.update(v);
                MsgBox.alert(this, "Cập nhật Vé thành công!");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void delete() {
        try {
            int[] rows = tblVe.getSelectedRows();
            if (rows.length > 0
                    && MsgBox.confirm(this, "Bạn muốn xóa vé này? ")) {
                for (int row : rows) {
                    int mave = (Integer) tblVe.getValueAt(row, 0);
                    dao.delete(mave);
                }
                this.fillTable();
                MsgBox.alert(this, "Xóa vé thành công!");
            }

        } catch (Exception e) {
            MsgBox.alert(this, "Xóa vé thất bại!");
            e.printStackTrace();
        }

    }

    private void xuatFile() {
        try {
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet sheet = workbook.createSheet("Vé");

            HSSFRow rows = null;// tạo hàng
            Cell cell = null;

            rows = sheet.createRow(3);// cách 3 dòng

            cell = rows.createCell(0, CellType.STRING);
            cell.setCellValue("STT");

            cell = rows.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Vé");

            cell = rows.createCell(2, CellType.STRING);
            cell.setCellValue("Gía Vé");

            cell = rows.createCell(3, CellType.STRING);
            cell.setCellValue("Mã Ghế");

            cell = rows.createCell(4, CellType.STRING);
            cell.setCellValue("Mã KH");

            cell = rows.createCell(5, CellType.STRING);
            cell.setCellValue("Mã NV");

            cell = rows.createCell(6, CellType.STRING);
            cell.setCellValue("Mã LC");

            cell = rows.createCell(7, CellType.STRING);
            cell.setCellValue("Mã Phim");

            List<Ve1> listItem = dao.selectAll();
            if (listItem != null) {
                int s = listItem.size();
                for (int i = 0; i < s; i++) {
                    Ve1 ve = listItem.get(i);
                    rows = sheet.createRow(4 + 1);

                    cell = rows.createCell(0, CellType.NUMERIC);
                    cell.setCellValue(i + 1);

                    cell = rows.createCell(1, CellType.STRING);
                    cell.setCellValue(ve.getMaVe());

                    cell = rows.createCell(2, CellType.STRING);
                    cell.setCellValue(ve.getGiaVe());

                    cell = rows.createCell(3, CellType.STRING);
                    cell.setCellValue(ve.getMaGhe());

                    cell = rows.createCell(4, CellType.STRING);
                    cell.setCellValue(ve.getMaKH());

                    cell = rows.createCell(5, CellType.STRING);
                    cell.setCellValue(ve.getMaNV_TaiKhoan());

                    cell = rows.createCell(6, CellType.STRING);
                    cell.setCellValue(ve.getMaLC());

                    cell = rows.createCell(7, CellType.STRING);
                    cell.setCellValue(ve.getMaPhim());
                }
                //save fill
                File f = new File("D://Ve.xlsx");
                FileOutputStream fis = new FileOutputStream(f);
                workbook.write(fis);
                fis.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
