/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinesys.ui;

import com.cinesys.DAO.PhimDAO;
import com.cinesys.DAO.ThongKeDAO;
import com.cinesys.entity.Phim;
import com.cinesys.untils.Auth;
import com.cinesys.untils.MsgBox;
import com.cinesys.untils.XDate;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuanlva
 */
public class TrangChuJFrame extends javax.swing.JFrame {
    
    private int row;
    public static List<Object[]> listLC = new ArrayList<>();

    /**
     * Creates new form TrangChuJFrame
     */
    public TrangChuJFrame() {
        initComponents();
        initBanVe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblActor = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBanVe = new javax.swing.JButton();
        btnQuanLyPhim = new javax.swing.JButton();
        btnQuanLyVe = new javax.swing.JButton();
        btnQuanLyLichChieu = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachPhim = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblHinhPhim = new javax.swing.JLabel();
        lblTenPhim = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DateNgayXem = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cboSuatChieu = new javax.swing.JComboBox<>();
        btnDatVe = new javax.swing.JButton();
        lblChuChay = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JCheckBoxMenuItem();
        mniDoiMatKhau = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniThoat = new javax.swing.JCheckBoxMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniQuanLyVe = new javax.swing.JMenuItem();
        mniQuanLyPhim = new javax.swing.JMenuItem();
        mniQuanLyLichChieu = new javax.swing.JMenuItem();
        mniQuanLySuatChieu = new javax.swing.JMenuItem();
        mniQuanLyPhongChieu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniQuanLyKhachHang = new javax.swing.JMenuItem();
        mniQuanLyNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDanSuDung = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblActor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Man_Icon.png"))); // NOI18N

        lblTen.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblTen.setText("Tên: Lương Vũ Anh Tuấn");

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblRole.setText("Role: Trưởng phòng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblActor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole)
                            .addComponent(lblTen))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblActor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTen)
                .addGap(12, 12, 12)
                .addComponent(lblRole)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnBanVe.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnBanVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Ticker_Sale.png"))); // NOI18N
        btnBanVe.setText("Bán vé");
        btnBanVe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanVeActionPerformed(evt);
            }
        });

        btnQuanLyPhim.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnQuanLyPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Film_Manage.png"))); // NOI18N
        btnQuanLyPhim.setText("Quản lý phim");
        btnQuanLyPhim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyPhimActionPerformed(evt);
            }
        });

        btnQuanLyVe.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnQuanLyVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Ticket_Manage.png"))); // NOI18N
        btnQuanLyVe.setText("Quản lý vé");
        btnQuanLyVe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyVeActionPerformed(evt);
            }
        });

        btnQuanLyLichChieu.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnQuanLyLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/schedule-Film.png"))); // NOI18N
        btnQuanLyLichChieu.setText("Quản lý lịch chiếu");
        btnQuanLyLichChieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyLichChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyLichChieuActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/ThongKe.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/log_out.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBanVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyLichChieu, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnBanVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyPhim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyLichChieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat)
                .addContainerGap())
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/cinema-post.jpg"))); // NOI18N

        tblDanhSachPhim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên phim", "Đạo điễn", "Thời lượng", "Ngày khởi chiếu", "Tình trạng"
            }
        ));
        tblDanhSachPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhimMouseClicked(evt);
            }
        });
        tblDanhSachPhim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDanhSachPhimKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachPhim);

        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHinhPhim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhPhim.setText("Hinh");

        lblTenPhim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenPhim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenPhim.setText("Bố Già");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel8.setText("Ngày:");

        DateNgayXem.setDateFormatString("dd-MM-yyyy");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Suất chiếu:");

        cboSuatChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboSuatChieuMousePressed(evt);
            }
        });
        cboSuatChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSuatChieuActionPerformed(evt);
            }
        });

        btnDatVe.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnDatVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Booking-Ticket.png"))); // NOI18N
        btnDatVe.setText("Đặt vé");
        btnDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHinhPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenPhim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateNgayXem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDatVe)
                                    .addComponent(cboSuatChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinhPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTenPhim)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateNgayXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboSuatChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDatVe)
                .addContainerGap())
        );

        lblChuChay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblChuChay.setText("ngày 30/12/2021 ra mắt phim mới giảm giá 10%.....................");

        mnuHeThong.setText("Hệ Thống");

        mniDangXuat.setText("Đăng Xuất");
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Log out.png"))); // NOI18N
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);

        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Refresh.png"))); // NOI18N
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator1);

        mniThoat.setText("Thoát");
        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Stop.png"))); // NOI18N
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản Lý");

        mniQuanLyVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Ticket.png"))); // NOI18N
        mniQuanLyVe.setText("Quản lý vé");
        mniQuanLyVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyVeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQuanLyVe);

        mniQuanLyPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/Film-projector.png"))); // NOI18N
        mniQuanLyPhim.setText("Quản lý phim");
        mnuQuanLy.add(mniQuanLyPhim);

        mniQuanLyLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/schedule.png"))); // NOI18N
        mniQuanLyLichChieu.setText("Quản lý lịch chiếu");
        mnuQuanLy.add(mniQuanLyLichChieu);

        mniQuanLySuatChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/management-30.png"))); // NOI18N
        mniQuanLySuatChieu.setText("Quản lý suất chiếu");
        mnuQuanLy.add(mniQuanLySuatChieu);

        mniQuanLyPhongChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/cinema-30.png"))); // NOI18N
        mniQuanLyPhongChieu.setText("Quản lý phòng chiếu");
        mnuQuanLy.add(mniQuanLyPhongChieu);
        mnuQuanLy.add(jSeparator2);

        mniQuanLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/customer-30.png"))); // NOI18N
        mniQuanLyKhachHang.setText("Quản lý khách hàng");
        mnuQuanLy.add(mniQuanLyKhachHang);

        mniQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/staff-30.png"))); // NOI18N
        mniQuanLyNhanVien.setText("Quản lý nhân viên");
        mniQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQuanLyNhanVien);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setText("Thống Kê");
        jMenuBar1.add(mnuThongKe);

        mnuTroGiup.setText("Trợ Giúp");

        mniHuongDanSuDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinesys/icon/training-30.png"))); // NOI18N
        mniHuongDanSuDung.setText("Hướng dẫn sử dụng");
        mnuTroGiup.add(mniHuongDanSuDung);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChuChay, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblChuChay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanVeActionPerformed

    }//GEN-LAST:event_btnBanVeActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void cboSuatChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSuatChieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSuatChieuActionPerformed

    private void btnDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatVeActionPerformed
        this.openDatVe();
        
    }//GEN-LAST:event_btnDatVeActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniQuanLyVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniQuanLyVeActionPerformed

    private void mniQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyNhanVienActionPerformed
        this.openQuanLyNhanVien();
    }//GEN-LAST:event_mniQuanLyNhanVienActionPerformed

    private void tblDanhSachPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachPhimMouseClicked
        this.fillInfor();
    }//GEN-LAST:event_tblDanhSachPhimMouseClicked

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        if (txtTimKiem.getText().trim().toLowerCase().equals("tìm kiếm")) {
            txtTimKiem.setText("");
            txtTimKiem.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        String timKiem = txtTimKiem.getText().trim().toLowerCase();
        if (timKiem.equals("") || timKiem.equals("tìm kiếm")) {
            txtTimKiem.setText("Tìm kiếm");
            txtTimKiem.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtTimKiemFocusLost

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        this.fillTable();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tblDanhSachPhimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDanhSachPhimKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            fillInfor();
        }
    }//GEN-LAST:event_tblDanhSachPhimKeyReleased

    private void cboSuatChieuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboSuatChieuMousePressed
        String ten = lblTenPhim.getText();
        this.fillComboBox(ten);
    }//GEN-LAST:event_cboSuatChieuMousePressed

    private void btnQuanLyPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyPhimActionPerformed
        this.openQuanLyPhim();
    }//GEN-LAST:event_btnQuanLyPhimActionPerformed

    private void btnQuanLyVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyVeActionPerformed
        this.openQuanLyVe();
    }//GEN-LAST:event_btnQuanLyVeActionPerformed

    private void btnQuanLyLichChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyLichChieuActionPerformed
        this.quanLyLichChieu();
    }//GEN-LAST:event_btnQuanLyLichChieuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dispose();
        new LoginJDialogg(this, true).setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        this.openThongKe();
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateNgayXem;
    private javax.swing.JButton btnBanVe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDatVe;
    private javax.swing.JButton btnQuanLyLichChieu;
    private javax.swing.JButton btnQuanLyPhim;
    private javax.swing.JButton btnQuanLyVe;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cboSuatChieu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblActor;
    private javax.swing.JLabel lblChuChay;
    private javax.swing.JLabel lblHinhPhim;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenPhim;
    private javax.swing.JCheckBoxMenuItem mniDangXuat;
    private javax.swing.JCheckBoxMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniHuongDanSuDung;
    private javax.swing.JMenuItem mniQuanLyKhachHang;
    private javax.swing.JMenuItem mniQuanLyLichChieu;
    private javax.swing.JMenuItem mniQuanLyNhanVien;
    private javax.swing.JMenuItem mniQuanLyPhim;
    private javax.swing.JMenuItem mniQuanLyPhongChieu;
    private javax.swing.JMenuItem mniQuanLySuatChieu;
    private javax.swing.JMenuItem mniQuanLyVe;
    private javax.swing.JCheckBoxMenuItem mniThoat;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JTable tblDanhSachPhim;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    PhimDAO dao = new PhimDAO();
    ThongKeDAO tkDAO = new ThongKeDAO();
    javax.swing.Timer t;
    
    private void initBanVe() {
        this.setLocationRelativeTo(null); 
        new FormChaoJDialog(this, true).setVisible(true);
        new LoginJDialogg(this, true).setVisible(true);
        this.fillUser();
        //chạy chữ
        ActionListener a;
            a = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                            String lbl = lblChuChay.getText();
                                lbl = lbl.substring(1, lbl.length())+lbl.charAt(0);
                                lblChuChay.setText(lbl);
                            
                }
                
            };
        t = new javax.swing.Timer(1000, a);
        t.start();
        this.fillTable();
        tblDanhSachPhim.setRowSelectionInterval(0, 0);               
        this.row = tblDanhSachPhim.getSelectedRow();
        this.fillInfor();
    }

    public void fillUser() {
        lblTen.setText("Tên: "+Auth.user.getTen());
        String vaiTro;
        if (Auth.user.getVaiTro()) {
            vaiTro="Trưởng phòng";
        }else vaiTro="Nhân viên";
        lblRole.setText("Role: "+vaiTro);
        ImageIcon image=new ImageIcon(Auth.user.getAnhNV());
        Image img=image.getImage();
        ImageIcon icon=new ImageIcon(img.getScaledInstance(lblActor.getWidth(), lblActor.getHeight(), img.SCALE_SMOOTH));
        lblActor.setText("");
        lblActor.setIcon(icon);
    }

    public void fillTable() {
        tblDanhSachPhim.setSelectionMode(0);
        DefaultTableModel model = (DefaultTableModel) tblDanhSachPhim.getModel();
        model.setRowCount(0);
        List<Phim> listSelected = new ArrayList<>();
        String timKiem = txtTimKiem.getText().trim().toLowerCase();
        try {
            List<Phim> list = dao.selectAll();
            if (!timKiem.equals("tìm kiếm")) {
                for (int i = 0; i < list.size(); i++) {
                    Phim entity = list.get(i);
                    if (entity.getTenPhim().toLowerCase().contains(timKiem)) {
                        listSelected.add(entity);
                    } else if (entity.getDaoDien().toLowerCase().contains(timKiem)) {
                        listSelected.add(entity);
                    }
                }
            } else {
                listSelected = list;
            }
            
            for (Phim phim : listSelected) {
                Date ngayKC = phim.getNgayKhoiChieu();
                Object status;
                Date now = new Date();
                if (ngayKC.after(now)) {
                    status = "Chưa khởi chiếu";
                } else {
                    status = "Đang chiếu";
                }
                Object[] row = {
                    phim.getTenPhim(),
                    phim.getDaoDien(),
                    phim.getThoiLuong(),
                    phim.getNgayKhoiChieu(),
                    status,};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi dữ liệu");
            throw new RuntimeException(e);
        }
        
    }
    
    public void fillInfor() {
        this.row = tblDanhSachPhim.getSelectedRow();
        String tenPhim = (String) tblDanhSachPhim.getValueAt(this.row, 0);
        try {
            Phim entity = dao.selectByPhim(tenPhim);
            this.setForm(entity);
            this.fillComboBox(entity.getTenPhim());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    
    private void setForm(Phim entity) {
        ImageIcon image = new ImageIcon(entity.getHinhAnh());
        Image img = image.getImage();
        ImageIcon icon = new ImageIcon(img.getScaledInstance(lblHinhPhim.getWidth(), lblHinhPhim.getHeight(), img.SCALE_SMOOTH));
        lblHinhPhim.setText("");
        lblHinhPhim.setIcon(icon);
        lblTenPhim.setText(entity.getTenPhim());
        String trangThai = (String) tblDanhSachPhim.getValueAt(this.row, 4);
        if (trangThai.toLowerCase().equals("đang chiếu")) {
            DateNgayXem.setDate(new Date());
        } else {
            DateNgayXem.setDate(entity.getNgayKhoiChieu());
        }
    }
    
    private void fillComboBox(String tenPhim) {
        List<Object[]> list = tkDAO.getSuatChieu(tenPhim);
        String dateChooser = XDate.toString(DateNgayXem.getDate(), "yyyy-MM-dd");
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSuatChieu.getModel();
        model.removeAllElements();
        for (Object[] obj : list) {
            String date = String.valueOf(obj[0]);
            if (dateChooser.equals(date)) {
                model.addElement(obj[1]);
            }
        }
    }
    
    public void openDatVe() {
        String tenP = lblTenPhim.getText();
        Date ngayChieu = DateNgayXem.getDate();
        Date suatChieu = (Date) cboSuatChieu.getSelectedItem();
        listLC = tkDAO.getSuatChieuRap(tenP, ngayChieu, suatChieu);
        new DatVeJDialog1(this, true).setVisible(true);
    }
    
    private void openQuanLyPhim() {
        QuanLyPhimJFrame qlPhim = new QuanLyPhimJFrame();
        qlPhim.setVisible(true);
    }
    
    private void openQuanLyVe() {
        new QuanLyVe(this, true).setVisible(true);
    }
    
    private void quanLyLichChieu() {
        QuanLiLichChieu qlLC = new QuanLiLichChieu();
        qlLC.setVisible(true);
    }
    
    private void openQuanLyNhanVien() {
//        QuanLyNhanVienJFrame qlNV = new QuanLyNhanVienJFrame();
//        qlNV.setVisible(true);
    }
    
    private void openThongKe() {
        ThongKe tk = new ThongKe();
        tk.setVisible(true);
    }
}
